[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rsa = "0.9.8"
rand = "0.8"
sha2 = "0.10"
shared = { path = "../shared" }
tokio = { version = "1.47.0", features = ["full"] }
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
